### ISSUE TITLE
Do these lines have their parameters crossed?

### ISSUE THREAD

**Issue by Tim-Magee** [searchmarkers/mark-my-search#138]
These are the lines:

https://github.com/searchmarkers/mark-my-search/blob/c8ce2d61947c0b7b64adb1616164098fa2081a79/src/pages/popup-build.ts#L418C1-L420C1

I ask because after a restart the two search types are swapped. If you previously had 'whole' selected then after the restart you have 'stem' selected, and (I think though I haven't checked) vice versa. It's not a critical failure but it's vexing enough to make me want to fix it. Sadly I'm not set up for extension building at home so I'm just monkeypatching the XPI to experiment with it.

There's another source file in the XPI with the same two swapped-parameter lines, popup.js, but I didn't spot it yet in the repo, perhaps it's built as part of creating the XPI?

Anyhow, apart from this quibble MMS has been working very well.

**Comment by ator-dev** [comment]
Yes! Good spot, thanks for debugging it for me. You've caught me just as I am restarting work on Mark My Search, as I've had a lot going on in recent months.

`popup.js` is actually not meant to be in the XPI, it seems my build script was leaving old generated files around and zipping them. I have now fixed the script which will reduce package size, thank you for that too!

To be honest, the "keyword lists" interface has several bugs, I need to get around to rewriting it. I'll definitely fix this before the next version though, hopefully coming out soon (:
