### ISSUE TITLE
[Feature request] More opaque / solid search bar

### ISSUE THREAD

**Issue by vatterspun** [searchmarkers/mark-my-search#67]
This is far from critical, just something that bothers me personally.  Feel free to decline this suggestion.

---

CURRENT BEHAVIOR

In dark mode when scrolling over certain text, the search terms at the top become invisible.  In the case below "search" and "add" are hard to read.

![image](https://user-images.githubusercontent.com/1289134/203360750-ce070175-f2d8-44e1-8194-fb4ff6f2b758.png)

REQUESTED BEHAVIOR

An option to either reduce or remove transparency (a solid background) behind the search terms.

![image](https://user-images.githubusercontent.com/1289134/203362294-11707420-422c-4c12-a614-93ece750cdbf.png)

**Comment by ator-dev** [comment]
Added an option for keyword buttons, along with 3 other accessibility/style options for the toolbar. Increased default keyword button opacity for increased readability and made toolbar style more dynamic. Currently targeting 1.11.0 along with potential future improvements. Thanks!

![image](https://user-images.githubusercontent.com/66553618/203816795-134dfd8c-c915-4e15-b9f6-5e4647ecb441.png)
