### ISSUE TITLE
[feature request] F2 step through search results

### ISSUE THREAD

**Issue by jmdurant** [searchmarkers/mark-my-search#75]
Hi, great job with this extension! I was wondering if you could make an option to "select the text" when you step through the search results. (currently it places the cursur right in front of the text) I have documents that have wildcards (**) that I have to go through to edit.  I use your extension to automatically highlight them.  If I could then "F2" (forward) and "Shift-F2" (backward) through each of them to complete the edits.  
![f2](https://user-images.githubusercontent.com/8346344/207712008-5681a4a0-63cf-4011-8b1c-6b09664dbb3f.jpg)
This is a very common workflow for people working in medicine in electronic healthcare records (Epic)

**Comment by ator-dev** [comment]
Hey, glad you like the extension, and thanks for the feature request! The current behaviour is optimised to group 'highlights' together in order to jump through them more quickly; for this, it makes less sense to select the text as several 'highlights' may be in the same focused group.

That said, I like this idea for a separate, more simple stepper. Before I look into implementing it, would you mind giving me validation to use F2 / Shift+F2 as the default shortcut? Current shortcuts tend to use Alt and/or Shift combined with a letter, but I am open to other ideas.

**Comment by ator-dev** [comment]
Note: on Chromium-based browsers like Chrome and Edge, "default" shortcuts are limited to 4. of which I am currently assigning "Find in current tab", "Show/hide highlighting", and "Jump to next [/previous] mark". As such, I am unlikely to provide this by default except in Firefox - it will need to be assigned manually.

**Comment by jmdurant** [comment]
Hey, absolutely.  It doesn't have to be F2,  it could be any shortcut key, but in Epic, the most common EHR, we step through a document with F2.  (this post describes it, but is not important https://talk.automators.fm/t/way-to-use-text-placeholders-such-as-that-can-be-tabbed-through/3657 )
Anyways, the current functioning is perfect - I just wish is would select the "result" as it jumps to the next "result".  I can do it by  pressing "Ctrl+Shift+right arrow key".  Thanks!

**Comment by ator-dev** [comment]
Thank you for the information! Now targeting 'stepping' with default F2 / Shift+F2 for `v1.11`. I have decided that since several extensions and self-contained programs use F2 as a stepping method, and browsers tend to use F3 for the same purpose (which follows a similar pattern without conflicting), F2 is a good default choice. Existing and Chromium-based users must assign manually.

**Comment by ator-dev** [comment]
For the record, this is an area I have been thinking about recently, especially in relation to the upcoming merge with `paint` branch which will add an experimental highlighter and several refactorisations. Keyword jumping is changing a lot under the hood and should allow for a simpler stepping mode, addressing a more specific but consistent use-case.

**Comment by ator-dev** [comment]
@jmdurant Not specific to this issue, but I wanted to let you know - if you open the popup, you can go to a Keyword Lists tab which I think would be useful for you. Typing any name for your list will create one, and you can add any keywords (e.g. `**`) and URL patterns to always highlight them on automatically.

**Comment by jmdurant** [comment]
Hey! just wanted to let you know that it works amazing in Firefox. I have been using it without issue.  My work place is forcing chrome on us now though.  I went in to try the latest release on chrome and it doesn't work the same.  In firefox when I step through the found search terms it selects the search term (which is perfect to allow typing to replace).  In chrome it just places the cursor in front of the selected term so typing isn't replacing the search term.  example below:  
![stepthrough](https://user-images.githubusercontent.com/8346344/230630955-2ad1b278-172a-4a6e-8eab-573891220302.jpg)

**Comment by ator-dev** [comment]
Hi, I'm glad it's been working well in Firefox! It is annoying that workplaces like to force Chrome on people.

Are you sure you're using stepping? You should have something convenient assigned to these commands as so:

![image](https://user-images.githubusercontent.com/66553618/230663933-8777a93b-de05-48cb-b6f0-84ffbd5b2e91.png)

I can't find any major differences in Chrome, although I have identified some strange inconsistencies which I will try to address in a future update.

**Comment by ator-dev** [comment]
If is is stepping that's not working, can you let me know how to reproduce the issue please? If it's a workplace-specific website, it may help to find another place where the same problem occurs.

**Comment by jmdurant** [comment]
So sorry.  It works great - I had configured the keyboard shortcut for
"jump" instead of "step".  Thanks so much for help. Your extension has been
so helpful!

**Comment by ator-dev** [comment]
No worries! Your note was helpful actually, as it caused me to find inconsistencies which I would like to fix. Thank you for your kind comments, I appreciate it (:
