### ISSUE TITLE
Link from Firefox extension page to the support/github site is not correct I think

### ISSUE THREAD

**Issue by buckleyGI** [searchmarkers/mark-my-search#83]
When following the link on
https://addons.mozilla.org/en-US/firefox/addon/mark-my-search/
We get to 
https://github.com/ator-dev/mark-my-search/pulls

This is another repo where the the issue tab is not available?

![image](https://user-images.githubusercontent.com/2102864/211511715-d66bfad1-4fce-48bc-9e8f-d73265701ab7.png)

**Comment by ator-dev** [comment]
I understand now - turns out I never updated that link after moving repositories! That is my personal fork of the repo where I build pull requests. I have now fixed it, thanks for letting me know (:

**Comment by buckleyGI** [comment]
No problem :)
